
DROP TABLE IF EXISTS Player;
DROP TABLE IF EXISTS Tournament;
DROP TABLE IF EXISTS Course;
DROP TABLE IF EXISTS Round; 
DROP TABLE IF EXISTS Hole;
DROP TABLE IF EXISTS Statistics;
DROP TABLE IF EXISTS PlaysIn;


CREATE TABLE Player (
	PID	INTEGER,
	FName	TEXT,
	LName	TEXT,
	PRIMARY KEY(PID)
);

CREATE TABLE Tournament (
	TID	INTEGER,
	Name	TEXT,
	Date	TEXT,
	Major	INTEGER,
	PRIMARY KEY(TID)
);

CREATE TABLE Course (
	CID	INTEGER,
	Name	TEXT,
	City	TEXT,
	Country	TEXT,
	Length	INTEGER,
	Par	INTEGER,
	PRIMARY KEY (CID)
);

CREATE TABLE Round (
	PID	INTEGER,
	TID	INTEGER,
	Day	INTEGER,
	Score	INTEGER,
	Place	INTEGER,
	PRIMARY KEY(PID,TID),
	FOREIGN KEY(PID) REFERENCES Player(PID),
	FOREIGN KEY(TID) REFERENCES Tournament(TID)
);

CREATE TABLE Hole (
	Number	INTEGER,
	CID	INTEGER,
	Par	INTEGER,
	Rating	INTEGER,
	Yards	INTEGER,
	PRIMARY KEY(Number, CID),
	FOREIGN KEY(CID) REFERENCES Course(CID)
);

CREATE TABLE Statistics (
	PID 		INTEGER,
	TID		INTEGER,
	AvgDrvDistance	REAL,
	DrvAcc		REAL,
	GIRRank		INTEGER,
	GIRPerc		REAL,
	OnePutts	INTEGER,
	Saves		INTEGER,
	SavePerc	REAL,
	PRIMARY KEY(PID, TID),
	FOREIGN KEY(PID) REFERENCES Player(PID),
	FOREIGN KEY(TID) REFERENCES Tournament(TID) 
);

CREATE TABLE PlaysIn (
	PID 	INTEGER,
	TID 	INTEGER,
	WRThis	INTEGER,
	WRLast	INTEGER,
	PRIMARY KEY(PID, TID),
	FOREIGN KEY(PID) REFERENCES Player(PID),
	FOREIGN KEY(TID) REFERENCES Tournament(TID)
);